import { Board, Group, StickyNote, Connection } from '../types';

export interface DemoLandscape {
  board: Board;
  subtitle: string;
  notes: Omit<StickyNote, 'createdAt' | 'updatedAt'>[];
  groups: Omit<Group, 'createdAt' | 'updatedAt'>[];
  connections: Omit<Connection, 'createdAt'>[];
}

export const DEMO_LANDSCAPES: DemoLandscape[] = [
  // 1. PRIMARY DEFAULT LANDSCAPE: Welcome to Thoughtscape
  {
    board: {
      id: 'landscape_welcome',
      name: 'Welcome to Thoughtscape',
      description: 'See how thoughts can live together.',
      isDefault: true,
      createdAt: 1726041600000,
      updatedAt: 1726041600000,
    },
    subtitle: 'See how thoughts can live together.',
    groups: [
      {
        id: 'group_welcome_school',
        boardId: 'landscape_welcome',
        title: 'School — Class 10',
        description: 'Revision, board prep, and exam plans',
        color: 'blue',
        x: 60,
        y: 60,
        width: 610,
        height: 520,
        collapsed: false,
      },
      {
        id: 'group_welcome_college',
        boardId: 'landscape_welcome',
        title: 'College',
        description: 'Semester projects, ideas, and learning',
        color: 'yellow',
        x: 710,
        y: 60,
        width: 610,
        height: 520,
        collapsed: false,
      },
      {
        id: 'group_welcome_work',
        boardId: 'landscape_welcome',
        title: 'Work',
        description: 'Weekly priorities, meetings, and improvements',
        color: 'green',
        x: 60,
        y: 620,
        width: 610,
        height: 520,
        collapsed: false,
      },
      {
        id: 'group_welcome_life',
        boardId: 'landscape_welcome',
        title: 'Life',
        description: 'Personal notes, trip planning, and memory keeping',
        color: 'peach',
        x: 710,
        y: 620,
        width: 610,
        height: 520,
        collapsed: false,
      },
    ],
    notes: [
      // CLUSTER 1: School — Class 10
      {
        id: 'note_welcome_sci_rev',
        boardId: 'landscape_welcome',
        title: 'Science Revision',
        type: 'concept',
        color: 'blue', // Information / references
        content: 'Physics, Chemistry and Biology topics I want to revise before the board exams.',
        x: 90,
        y: 130,
        width: 260,
        height: 190,
        rotation: -1.2,
        zIndex: 1,
        tags: ['school', 'revision'],
        starred: true,
        pinned: false,
        groupId: 'group_welcome_school',
        learningState: 'understood',
      },
      {
        id: 'note_welcome_board_plan',
        boardId: 'landscape_welcome',
        title: 'Board Exam Plan',
        type: 'task',
        color: 'green', // Tasks / plans
        content: 'Finish Science revision → solve previous papers → review mistakes → final revision.',
        x: 380,
        y: 130,
        width: 260,
        height: 190,
        rotation: 1.1,
        zIndex: 2,
        tags: ['exam', 'plan'],
        starred: false,
        pinned: false,
        groupId: 'group_welcome_school',
        taskItems: [
          { id: 'bp1', text: 'Finish Science revision', completed: true },
          { id: 'bp2', text: 'Solve previous 5-year papers', completed: false },
          { id: 'bp3', text: 'Review formula mistake notes', completed: false },
          { id: 'bp4', text: 'Final full-length mock test', completed: false },
        ],
      },
      {
        id: 'note_welcome_school_mistakes',
        boardId: 'landscape_welcome',
        title: 'Things I Keep Forgetting',
        type: 'mistake',
        color: 'pink', // Important / remember
        content: 'Important formulas, definitions and diagrams that I need to revise again.',
        x: 90,
        y: 350,
        width: 260,
        height: 200,
        rotation: 0.8,
        zIndex: 3,
        tags: ['revision', 'mistakes'],
        starred: true,
        pinned: false,
        groupId: 'group_welcome_school',
        mistakeDetails: {
          whatIDid: 'Tried to memorize ray diagrams without practicing with a ruler and pencil',
          whyWrong: 'Arrows and focal points get mixed up during the exam',
          correctApproach: 'Draw and label 2 ray diagrams every morning',
          howToAvoid: 'Keep a 1-page summary chart pinned on the wall',
        },
      },

      // CLUSTER 2: College
      {
        id: 'note_welcome_semester_proj',
        boardId: 'landscape_welcome',
        title: 'Semester Project',
        type: 'task',
        color: 'green', // Tasks / plans
        content: 'Build the project → divide tasks → collect resources → prepare presentation.',
        x: 740,
        y: 130,
        width: 260,
        height: 190,
        rotation: -0.8,
        zIndex: 4,
        tags: ['college', 'project'],
        starred: true,
        pinned: false,
        groupId: 'group_welcome_college',
        taskItems: [
          { id: 'cp1', text: 'Build the project architecture', completed: true },
          { id: 'cp2', text: 'Divide tasks among teammates', completed: true },
          { id: 'cp3', text: 'Collect resources and papers', completed: false },
          { id: 'cp4', text: 'Prepare presentation deck', completed: false },
        ],
      },
      {
        id: 'note_welcome_things_to_learn',
        boardId: 'landscape_welcome',
        title: 'Things To Learn',
        type: 'idea',
        color: 'yellow', // Ideas / explore
        content: 'Topics, skills and tools I want to explore this semester.',
        x: 1030,
        y: 130,
        width: 260,
        height: 190,
        rotation: 1.4,
        zIndex: 5,
        tags: ['college', 'learning'],
        starred: false,
        pinned: false,
        groupId: 'group_welcome_college',
      },
      {
        id: 'note_welcome_assign_ideas',
        boardId: 'landscape_welcome',
        title: 'Assignment Ideas',
        type: 'idea',
        color: 'purple', // Questions / reflections
        content: 'Possible approaches, references and questions to discuss with classmates.',
        x: 740,
        y: 350,
        width: 260,
        height: 190,
        rotation: -1.3,
        zIndex: 6,
        tags: ['assignment'],
        starred: false,
        pinned: false,
        groupId: 'group_welcome_college',
      },

      // CLUSTER 3: Work
      {
        id: 'note_welcome_this_week_work',
        boardId: 'landscape_welcome',
        title: 'This Week at Work',
        type: 'task',
        color: 'green', // Tasks / plans
        content: 'Finish the presentation, review the report, attend the team meeting and follow up on pending tasks.',
        x: 90,
        y: 690,
        width: 260,
        height: 190,
        rotation: 0.6,
        zIndex: 7,
        tags: ['work', 'weekly'],
        starred: true,
        pinned: false,
        groupId: 'group_welcome_work',
      },
      {
        id: 'note_welcome_meeting_notes',
        boardId: 'landscape_welcome',
        title: 'Meeting Notes',
        type: 'concept',
        color: 'blue', // Information / references
        content: "Key decisions, action items and questions from today's discussion.",
        x: 380,
        y: 690,
        width: 260,
        height: 190,
        rotation: -0.9,
        zIndex: 8,
        tags: ['work', 'meeting'],
        starred: false,
        pinned: false,
        groupId: 'group_welcome_work',
      },
      {
        id: 'note_welcome_project_ideas',
        boardId: 'landscape_welcome',
        title: 'Project Ideas',
        type: 'idea',
        color: 'yellow', // Ideas / explore
        content: "Small improvements that could make our team's workflow easier.",
        x: 90,
        y: 910,
        width: 260,
        height: 190,
        rotation: 1.2,
        zIndex: 9,
        tags: ['work', 'ideas'],
        starred: false,
        pinned: false,
        groupId: 'group_welcome_work',
      },

      // CLUSTER 4: Life
      {
        id: 'note_welcome_remember',
        boardId: 'landscape_welcome',
        title: 'Things I Want To Remember',
        type: 'quote',
        color: 'pink', // Important / remember
        content: "Small reminders, important dates, ideas and lessons I don't want to lose.",
        quoteAuthor: 'Personal Note',
        x: 740,
        y: 690,
        width: 260,
        height: 190,
        rotation: -0.7,
        zIndex: 10,
        tags: ['life', 'personal'],
        starred: true,
        pinned: false,
        groupId: 'group_welcome_life',
      },
      {
        id: 'note_welcome_trip_plan',
        boardId: 'landscape_welcome',
        title: 'Trip Plan',
        type: 'task',
        color: 'peach', // Personal notes
        content: 'Places to visit → things to pack → bookings → food to try → memories to capture.',
        x: 1030,
        y: 690,
        width: 260,
        height: 190,
        rotation: 1.3,
        zIndex: 11,
        tags: ['travel', 'planning'],
        starred: false,
        pinned: false,
        groupId: 'group_welcome_life',
      },
      {
        id: 'note_welcome_books_ideas',
        boardId: 'landscape_welcome',
        title: 'Books & Ideas',
        type: 'concept',
        color: 'blue', // Information / references
        content: 'Interesting books, quotes, lessons and ideas worth coming back to.',
        x: 740,
        y: 910,
        width: 260,
        height: 190,
        rotation: -1.1,
        zIndex: 12,
        tags: ['books', 'ideas'],
        starred: false,
        pinned: false,
        groupId: 'group_welcome_life',
      },
    ],
    connections: [
      {
        id: 'conn_welcome_1',
        boardId: 'landscape_welcome',
        sourceId: 'note_welcome_sci_rev',
        targetId: 'note_welcome_board_plan',
        type: 'arrow',
        label: 'steps',
      },
      {
        id: 'conn_welcome_2',
        boardId: 'landscape_welcome',
        sourceId: 'note_welcome_semester_proj',
        targetId: 'note_welcome_assign_ideas',
        type: 'arrow',
        label: 'inspires',
      },
      {
        id: 'conn_welcome_3',
        boardId: 'landscape_welcome',
        sourceId: 'note_welcome_meeting_notes',
        targetId: 'note_welcome_this_week_work',
        type: 'arrow',
        label: 'action items',
      },
      {
        id: 'conn_welcome_4',
        boardId: 'landscape_welcome',
        sourceId: 'note_welcome_trip_plan',
        targetId: 'note_welcome_remember',
        type: 'arrow',
        label: 'moments',
      },
    ],
  },

  // 2. SCHOOL: Class 10 — Board Preparation
  {
    board: {
      id: 'landscape_class10',
      name: 'Class 10 — Board Preparation',
      description: 'Organize revision, questions and exam plans.',
      createdAt: 1726041601000,
      updatedAt: 1726041601000,
    },
    subtitle: 'Organize revision, questions and exam plans.',
    groups: [
      {
        id: 'group_c10_sci',
        boardId: 'landscape_class10',
        title: 'Science',
        description: 'Physics, Chemistry & Biology topics',
        color: 'blue',
        x: 60,
        y: 60,
        width: 880,
        height: 270,
        collapsed: false,
      },
      {
        id: 'group_c10_math',
        boardId: 'landscape_class10',
        title: 'Mathematics',
        description: 'Formulas and key concepts',
        color: 'peach',
        x: 60,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'group_c10_social',
        boardId: 'landscape_class10',
        title: 'Social Science',
        description: 'History timelines & Geography maps',
        color: 'yellow',
        x: 670,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'group_c10_lang',
        boardId: 'landscape_class10',
        title: 'Languages',
        description: 'Grammar and writing formats',
        color: 'purple',
        x: 60,
        y: 660,
        width: 380,
        height: 270,
        collapsed: false,
      },
      {
        id: 'group_c10_plan',
        boardId: 'landscape_class10',
        title: 'Exam Plan',
        description: 'Revision schedule and practice papers',
        color: 'green',
        x: 470,
        y: 660,
        width: 780,
        height: 270,
        collapsed: false,
      },
    ],
    notes: [
      {
        id: 'c10_n1',
        boardId: 'landscape_class10',
        title: 'Physics — Electricity',
        type: 'concept',
        color: 'blue',
        content: "Ohm's Law (V = IR), series and parallel resistance formulas, Joule's heating law.",
        x: 90,
        y: 120,
        width: 250,
        height: 180,
        rotation: -1,
        zIndex: 1,
        tags: ['physics', 'science'],
        starred: true,
        pinned: false,
        groupId: 'group_c10_sci',
      },
      {
        id: 'c10_n2',
        boardId: 'landscape_class10',
        title: 'Chemistry — Reactions',
        type: 'concept',
        color: 'yellow',
        content: 'Balancing chemical equations, displacement vs double displacement, redox reactions.',
        x: 370,
        y: 120,
        width: 250,
        height: 180,
        rotation: 1.2,
        zIndex: 2,
        tags: ['chemistry', 'science'],
        starred: false,
        pinned: false,
        groupId: 'group_c10_sci',
      },
      {
        id: 'c10_n3',
        boardId: 'landscape_class10',
        title: 'Biology — Life Processes',
        type: 'concept',
        color: 'green',
        content: 'Nutrition in plants and humans, double circulation in heart, nephron structure.',
        x: 650,
        y: 120,
        width: 260,
        height: 180,
        rotation: -0.6,
        zIndex: 3,
        tags: ['biology', 'science'],
        starred: false,
        pinned: false,
        groupId: 'group_c10_sci',
      },
      {
        id: 'c10_n4',
        boardId: 'landscape_class10',
        title: 'Maths — Quadratic Equations',
        type: 'concept',
        color: 'peach',
        content: 'Standard form ax² + bx + c = 0. Discriminant D = b² - 4ac. Nature of roots.',
        x: 90,
        y: 420,
        width: 250,
        height: 180,
        rotation: 0.9,
        zIndex: 4,
        tags: ['maths', 'equations'],
        starred: true,
        pinned: false,
        groupId: 'group_c10_math',
      },
      {
        id: 'c10_n5',
        boardId: 'landscape_class10',
        title: 'Maths — Trigonometry',
        type: 'concept',
        color: 'purple',
        content: 'Values table (0°, 30°, 45°, 60°, 90°). Identities: sin²θ + cos²θ = 1. Heights & distances.',
        x: 360,
        y: 420,
        width: 250,
        height: 180,
        rotation: -1.3,
        zIndex: 5,
        tags: ['maths', 'trig'],
        starred: false,
        pinned: false,
        groupId: 'group_c10_math',
      },
      {
        id: 'c10_n6',
        boardId: 'landscape_class10',
        title: 'History — Important Dates',
        type: 'concept',
        color: 'blue',
        content: 'Nationalism timeline: Non-Cooperation Movement, Dandi March, Simon Commission.',
        x: 700,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.1,
        zIndex: 6,
        tags: ['history', 'social'],
        starred: false,
        pinned: false,
        groupId: 'group_c10_social',
      },
      {
        id: 'c10_n7',
        boardId: 'landscape_class10',
        title: 'Geography — Maps',
        type: 'concept',
        color: 'yellow',
        content: 'Major soil types, major dams, river basins, coal and iron ore fields for map pointing.',
        x: 970,
        y: 420,
        width: 250,
        height: 180,
        rotation: -0.7,
        zIndex: 7,
        tags: ['geography', 'social'],
        starred: false,
        pinned: false,
        groupId: 'group_c10_social',
      },
      {
        id: 'c10_n8',
        boardId: 'landscape_class10',
        title: 'English — Writing Practice',
        type: 'idea',
        color: 'peach',
        content: 'Formal letter format, analytical paragraph structure, error correction rules.',
        x: 90,
        y: 720,
        width: 250,
        height: 180,
        rotation: 0.8,
        zIndex: 8,
        tags: ['english', 'writing'],
        starred: false,
        pinned: false,
        groupId: 'group_c10_lang',
      },
      {
        id: 'c10_n9',
        boardId: 'landscape_class10',
        title: 'Revision Checklist',
        type: 'task',
        color: 'green',
        content: 'Complete 1 sample paper every 2 days, review weak areas, practice timed drawing.',
        x: 500,
        y: 720,
        width: 230,
        height: 180,
        rotation: -1,
        zIndex: 9,
        tags: ['checklist', 'revision'],
        starred: true,
        pinned: false,
        groupId: 'group_c10_plan',
      },
      {
        id: 'c10_n10',
        boardId: 'landscape_class10',
        title: 'Previous Year Papers',
        type: 'task',
        color: 'green',
        content: 'Solve last 5 years papers for Science and Maths. Mark recurring 5-mark questions.',
        x: 750,
        y: 720,
        width: 230,
        height: 180,
        rotation: 1.4,
        zIndex: 10,
        tags: ['papers', 'pyq'],
        starred: false,
        pinned: false,
        groupId: 'group_c10_plan',
      },
      {
        id: 'c10_n11',
        boardId: 'landscape_class10',
        title: 'Topics I Need Help With',
        type: 'mistake',
        color: 'pink',
        content: "Trigonometry proof questions, magnetic effects Fleming's left hand rule — ask teacher tomorrow.",
        x: 1000,
        y: 720,
        width: 230,
        height: 180,
        rotation: -0.5,
        zIndex: 11,
        tags: ['doubts', 'help'],
        starred: true,
        pinned: false,
        groupId: 'group_c10_plan',
      },
    ],
    connections: [
      {
        id: 'conn_c10_1',
        boardId: 'landscape_class10',
        sourceId: 'c10_n1',
        targetId: 'c10_n9',
        type: 'arrow',
        label: 'revise',
      },
      {
        id: 'conn_c10_2',
        boardId: 'landscape_class10',
        sourceId: 'c10_n4',
        targetId: 'c10_n10',
        type: 'arrow',
        label: 'solve',
      },
      {
        id: 'conn_c10_3',
        boardId: 'landscape_class10',
        sourceId: 'c10_n11',
        targetId: 'c10_n9',
        type: 'arrow',
        label: 'follow up',
      },
    ],
  },

  // 3. COLLEGE: College Semester
  {
    board: {
      id: 'landscape_college',
      name: 'College Semester',
      description: 'Keep projects, assignments and ideas connected.',
      createdAt: 1726041602000,
      updatedAt: 1726041602000,
    },
    subtitle: 'Keep projects, assignments and ideas connected.',
    groups: [
      {
        id: 'grp_clg_subj',
        boardId: 'landscape_college',
        title: 'Subjects & Revision',
        description: 'Core semester courses and notes',
        color: 'blue',
        x: 60,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_clg_proj',
        boardId: 'landscape_college',
        title: 'Projects & Research',
        description: 'Team deliverables and experiments',
        color: 'yellow',
        x: 670,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_clg_assign',
        boardId: 'landscape_college',
        title: 'Assignments & Deadlines',
        description: 'Weekly homework and lab submissions',
        color: 'pink',
        x: 60,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_clg_career',
        boardId: 'landscape_college',
        title: 'Exams & Career Ideas',
        description: 'Preparation, portfolio, and goals',
        color: 'green',
        x: 670,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
    ],
    notes: [
      {
        id: 'clg_n1',
        boardId: 'landscape_college',
        title: 'Topics to Revise',
        type: 'concept',
        color: 'blue',
        content: 'Database indexing B+ trees, network TCP handshake vs UDP, operating system virtual memory.',
        x: 90,
        y: 120,
        width: 250,
        height: 180,
        rotation: -0.9,
        zIndex: 1,
        tags: ['revision', 'study'],
        starred: true,
        pinned: false,
        groupId: 'grp_clg_subj',
      },
      {
        id: 'clg_n2',
        boardId: 'landscape_college',
        title: 'Things to Ask Professor',
        type: 'question',
        color: 'purple',
        content: 'Clarify question 3 on caching strategies. Ask for recommended research papers on distributed consensus.',
        x: 360,
        y: 120,
        width: 250,
        height: 180,
        rotation: 1.2,
        zIndex: 2,
        tags: ['prof', 'questions'],
        starred: false,
        pinned: false,
        groupId: 'grp_clg_subj',
      },
      {
        id: 'clg_n3',
        boardId: 'landscape_college',
        title: 'Semester Project',
        type: 'task',
        color: 'green',
        content: 'Finalize topic with advisor → write system architecture draft → split frontend and backend tasks with team.',
        x: 700,
        y: 120,
        width: 250,
        height: 180,
        rotation: -1.1,
        zIndex: 3,
        tags: ['project', 'team'],
        starred: true,
        pinned: false,
        groupId: 'grp_clg_proj',
      },
      {
        id: 'clg_n4',
        boardId: 'landscape_college',
        title: 'Research Ideas',
        type: 'idea',
        color: 'yellow',
        content: 'Explore offline-first sync using local IndexedDB and lightweight replication algorithms.',
        x: 970,
        y: 120,
        width: 250,
        height: 180,
        rotation: 1.4,
        zIndex: 4,
        tags: ['research', 'ideas'],
        starred: false,
        pinned: false,
        groupId: 'grp_clg_proj',
      },
      {
        id: 'clg_n5',
        boardId: 'landscape_college',
        title: 'Assignment Deadlines',
        type: 'task',
        color: 'pink',
        content: 'Operating systems lab due Thursday. Database schema normalization exercise due next Monday.',
        x: 90,
        y: 420,
        width: 250,
        height: 180,
        rotation: 0.7,
        zIndex: 5,
        tags: ['deadline', 'assignment'],
        starred: true,
        pinned: false,
        groupId: 'grp_clg_assign',
      },
      {
        id: 'clg_n6',
        boardId: 'landscape_college',
        title: 'Project References',
        type: 'concept',
        color: 'blue',
        content: 'Useful GitHub repositories, documentation links, and benchmark tools to evaluate performance.',
        x: 360,
        y: 420,
        width: 250,
        height: 180,
        rotation: -1,
        zIndex: 6,
        tags: ['references', 'tools'],
        starred: false,
        pinned: false,
        groupId: 'grp_clg_assign',
      },
      {
        id: 'clg_n7',
        boardId: 'landscape_college',
        title: 'Exam Preparation',
        type: 'task',
        color: 'green',
        content: 'Organize past mid-term papers, form study group for mock quiz on Saturday evening.',
        x: 700,
        y: 420,
        width: 250,
        height: 180,
        rotation: -0.5,
        zIndex: 7,
        tags: ['exams', 'prep'],
        starred: false,
        pinned: false,
        groupId: 'grp_clg_career',
      },
      {
        id: 'clg_n8',
        boardId: 'landscape_college',
        title: 'Career Ideas',
        type: 'idea',
        color: 'peach',
        content: 'Update portfolio site, polish resume with recent project highlights, prepare interview notes.',
        x: 970,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.3,
        zIndex: 8,
        tags: ['career', 'goals'],
        starred: false,
        pinned: false,
        groupId: 'grp_clg_career',
      },
    ],
    connections: [
      {
        id: 'conn_clg_1',
        boardId: 'landscape_college',
        sourceId: 'clg_n3',
        targetId: 'clg_n6',
        type: 'arrow',
        label: 'references',
      },
      {
        id: 'conn_clg_2',
        boardId: 'landscape_college',
        sourceId: 'clg_n1',
        targetId: 'clg_n7',
        type: 'arrow',
        label: 'prepares for',
      },
      {
        id: 'conn_clg_3',
        boardId: 'landscape_college',
        sourceId: 'clg_n2',
        targetId: 'clg_n5',
        type: 'arrow',
        label: 'unblocks',
      },
    ],
  },

  // 4. WORK: Work & Projects
  {
    board: {
      id: 'landscape_work',
      name: 'Work & Projects',
      description: 'Bring tasks, meetings and project thinking together.',
      createdAt: 1726041603000,
      updatedAt: 1726041603000,
    },
    subtitle: 'Bring tasks, meetings and project thinking together.',
    groups: [
      {
        id: 'grp_work_today',
        boardId: 'landscape_work',
        title: 'Current Work & Priorities',
        description: 'Active tasks and daily focus',
        color: 'green',
        x: 60,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_work_strategy',
        boardId: 'landscape_work',
        title: 'Meetings & Strategy',
        description: 'Roadmaps, syncs, and client notes',
        color: 'blue',
        x: 670,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_work_followup',
        boardId: 'landscape_work',
        title: 'Follow-ups & Ideas',
        description: 'Process improvements and manager 1:1',
        color: 'yellow',
        x: 60,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_work_longterm',
        boardId: 'landscape_work',
        title: 'Long-Term & Next Week',
        description: 'Upcoming milestones and planning',
        color: 'peach',
        x: 670,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
    ],
    notes: [
      {
        id: 'wrk_n1',
        boardId: 'landscape_work',
        title: "Today's Priorities",
        type: 'task',
        color: 'green',
        content: '1. Finalize Q3 roadmap slide\n2. Review teammate pull request\n3. Send client status update by 4 PM',
        x: 90,
        y: 120,
        width: 250,
        height: 180,
        rotation: -0.8,
        zIndex: 1,
        tags: ['today', 'priority'],
        starred: true,
        pinned: false,
        groupId: 'grp_work_today',
      },
      {
        id: 'wrk_n2',
        boardId: 'landscape_work',
        title: 'Things to Follow Up',
        type: 'task',
        color: 'pink',
        content: 'Check with design team on color tokens. Confirm staging deployment URL with DevOps.',
        x: 360,
        y: 120,
        width: 250,
        height: 180,
        rotation: 1.1,
        zIndex: 2,
        tags: ['followup', 'tasks'],
        starred: false,
        pinned: false,
        groupId: 'grp_work_today',
      },
      {
        id: 'wrk_n3',
        boardId: 'landscape_work',
        title: 'Team Meeting',
        type: 'concept',
        color: 'blue',
        content: 'Standup at 10:30 AM: Discuss blocker on API rate limiting, align on release target for next sprint.',
        x: 700,
        y: 120,
        width: 250,
        height: 180,
        rotation: -1.2,
        zIndex: 3,
        tags: ['meeting', 'team'],
        starred: false,
        pinned: false,
        groupId: 'grp_work_strategy',
      },
      {
        id: 'wrk_n4',
        boardId: 'landscape_work',
        title: 'Project Roadmap',
        type: 'concept',
        color: 'blue',
        content: 'Phase 1: Core performance boost\nPhase 2: Real-time visual sync\nPhase 3: Public API beta launch',
        x: 970,
        y: 120,
        width: 250,
        height: 180,
        rotation: 0.9,
        zIndex: 4,
        tags: ['roadmap', 'strategy'],
        starred: true,
        pinned: false,
        groupId: 'grp_work_strategy',
      },
      {
        id: 'wrk_n5',
        boardId: 'landscape_work',
        title: 'Process Improvement Idea',
        type: 'idea',
        color: 'yellow',
        content: "Automate weekly progress summary emails to save 45 minutes of manual prep every Friday.",
        x: 90,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.4,
        zIndex: 5,
        tags: ['ideas', 'process'],
        starred: true,
        pinned: false,
        groupId: 'grp_work_followup',
      },
      {
        id: 'wrk_n6',
        boardId: 'landscape_work',
        title: 'Questions for Manager',
        type: 'question',
        color: 'purple',
        content: 'Discuss bandwidth for upcoming infrastructure migration. Ask about attending upcoming tech conference.',
        x: 360,
        y: 420,
        width: 250,
        height: 180,
        rotation: -1,
        zIndex: 6,
        tags: ['1on1', 'questions'],
        starred: false,
        pinned: false,
        groupId: 'grp_work_followup',
      },
      {
        id: 'wrk_n7',
        boardId: 'landscape_work',
        title: 'Client Notes',
        type: 'concept',
        color: 'peach',
        content: 'Client requested simpler dashboard export options and faster search filtering on large accounts.',
        x: 700,
        y: 420,
        width: 250,
        height: 180,
        rotation: -0.6,
        zIndex: 7,
        tags: ['client', 'feedback'],
        starred: false,
        pinned: false,
        groupId: 'grp_work_longterm',
      },
      {
        id: 'wrk_n8',
        boardId: 'landscape_work',
        title: 'Next Week',
        type: 'task',
        color: 'green',
        content: 'Kick off customer feedback interviews, prepare sprint planning backlog, review server metrics.',
        x: 970,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.2,
        zIndex: 8,
        tags: ['planning', 'nextweek'],
        starred: false,
        pinned: false,
        groupId: 'grp_work_longterm',
      },
    ],
    connections: [
      {
        id: 'conn_wrk_1',
        boardId: 'landscape_work',
        sourceId: 'wrk_n3',
        targetId: 'wrk_n2',
        type: 'arrow',
        label: 'generates',
      },
      {
        id: 'conn_wrk_2',
        boardId: 'landscape_work',
        sourceId: 'wrk_n4',
        targetId: 'wrk_n1',
        type: 'arrow',
        label: 'guides',
      },
      {
        id: 'conn_wrk_3',
        boardId: 'landscape_work',
        sourceId: 'wrk_n5',
        targetId: 'wrk_n6',
        type: 'arrow',
        label: 'discuss in 1:1',
      },
    ],
  },

  // 5. PERSONAL: Personal Life
  {
    board: {
      id: 'landscape_personal',
      name: 'Personal Life',
      description: 'Plans, ideas, memories and things worth remembering.',
      createdAt: 1726041604000,
      updatedAt: 1726041604000,
    },
    subtitle: 'Plans, ideas, memories and things worth remembering.',
    groups: [
      {
        id: 'grp_per_home',
        boardId: 'landscape_personal',
        title: 'Home & Weekend',
        description: 'Routines, DIY, and weekend plans',
        color: 'peach',
        x: 60,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_per_travel',
        boardId: 'landscape_personal',
        title: 'Travel & Goals',
        description: 'Getaways, hobbies, and personal targets',
        color: 'yellow',
        x: 670,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_per_ideas',
        boardId: 'landscape_personal',
        title: 'Books & Ideas',
        description: 'Reading list and interesting thoughts',
        color: 'blue',
        x: 60,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_per_remember',
        boardId: 'landscape_personal',
        title: 'Things To Remember',
        description: 'Important dates, quotes, and lessons',
        color: 'pink',
        x: 670,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
    ],
    notes: [
      {
        id: 'per_n1',
        boardId: 'landscape_personal',
        title: 'Weekend Plan',
        type: 'task',
        color: 'green',
        content: 'Saturday morning farmers market, bike ride along the river, dinner with friends at 7 PM.',
        x: 90,
        y: 120,
        width: 250,
        height: 180,
        rotation: -0.9,
        zIndex: 1,
        tags: ['weekend', 'life'],
        starred: true,
        pinned: false,
        groupId: 'grp_per_home',
      },
      {
        id: 'per_n2',
        boardId: 'landscape_personal',
        title: 'Home Improvements',
        type: 'task',
        color: 'peach',
        content: 'Fix bedroom bookshelf, organize desk cables, get 2 indoor plants for natural sunlight corner.',
        x: 360,
        y: 120,
        width: 250,
        height: 180,
        rotation: 1.2,
        zIndex: 2,
        tags: ['home', 'diy'],
        starred: false,
        pinned: false,
        groupId: 'grp_per_home',
      },
      {
        id: 'per_n3',
        boardId: 'landscape_personal',
        title: 'Trip Ideas',
        type: 'idea',
        color: 'yellow',
        content: 'Mountain getaway for autumn: look at scenic train routes, cozy cabins with hiking trails nearby.',
        x: 700,
        y: 120,
        width: 250,
        height: 180,
        rotation: -1.3,
        zIndex: 3,
        tags: ['travel', 'vacation'],
        starred: true,
        pinned: false,
        groupId: 'grp_per_travel',
      },
      {
        id: 'per_n4',
        boardId: 'landscape_personal',
        title: 'Personal Goals',
        type: 'concept',
        color: 'yellow',
        content: 'Run 5K twice a week, cook one new recipe every weekend, keep phone out of bedroom after 10 PM.',
        x: 970,
        y: 120,
        width: 250,
        height: 180,
        rotation: 0.8,
        zIndex: 4,
        tags: ['goals', 'habits'],
        starred: false,
        pinned: false,
        groupId: 'grp_per_travel',
      },
      {
        id: 'per_n5',
        boardId: 'landscape_personal',
        title: 'Books to Read',
        type: 'concept',
        color: 'blue',
        content: '• The Psychology of Money\n• Atomic Habits\n• A Short History of Nearly Everything\n• Thinking in Systems',
        x: 90,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.1,
        zIndex: 5,
        tags: ['books', 'reading'],
        starred: true,
        pinned: false,
        groupId: 'grp_per_ideas',
      },
      {
        id: 'per_n6',
        boardId: 'landscape_personal',
        title: 'Things to Buy',
        type: 'task',
        color: 'peach',
        content: 'Filter replacement for coffee machine, warm hiking socks, notebook refills, organic potting soil.',
        x: 360,
        y: 420,
        width: 250,
        height: 180,
        rotation: -0.7,
        zIndex: 6,
        tags: ['shopping', 'home'],
        starred: false,
        pinned: false,
        groupId: 'grp_per_ideas',
      },
      {
        id: 'per_n7',
        boardId: 'landscape_personal',
        title: 'Important Dates',
        type: 'quote',
        color: 'pink',
        content: "Mom's birthday: Oct 14.\nAnniversary dinner: Nov 3.\nCar annual service: Nov 20.",
        quoteAuthor: 'Calendar Reminders',
        x: 700,
        y: 420,
        width: 250,
        height: 180,
        rotation: -1.1,
        zIndex: 7,
        tags: ['calendar', 'dates'],
        starred: true,
        pinned: false,
        groupId: 'grp_per_remember',
      },
      {
        id: 'per_n8',
        boardId: 'landscape_personal',
        title: "Things I Don't Want to Forget",
        type: 'quote',
        color: 'purple',
        content: '"Rest is not a reward for work — it is an essential part of doing good work."',
        quoteAuthor: 'Life Lesson',
        x: 970,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.3,
        zIndex: 8,
        tags: ['mindset', 'quotes'],
        starred: true,
        pinned: false,
        groupId: 'grp_per_remember',
      },
    ],
    connections: [
      {
        id: 'conn_per_1',
        boardId: 'landscape_personal',
        sourceId: 'per_n2',
        targetId: 'per_n6',
        type: 'arrow',
        label: 'needs items',
      },
      {
        id: 'conn_per_2',
        boardId: 'landscape_personal',
        sourceId: 'per_n3',
        targetId: 'per_n4',
        type: 'arrow',
        label: 'planned for',
      },
      {
        id: 'conn_per_3',
        boardId: 'landscape_personal',
        sourceId: 'per_n8',
        targetId: 'per_n4',
        type: 'arrow',
        label: 'inspires',
      },
    ],
  },

  // 6. MATURE / OLDER USER / MEMORIES: My Life & Memories
  {
    board: {
      id: 'landscape_memories',
      name: 'My Life & Memories',
      description: 'A visual place for experiences, people and ideas.',
      createdAt: 1726041605000,
      updatedAt: 1726041605000,
    },
    subtitle: 'A visual place for experiences, people and ideas.',
    groups: [
      {
        id: 'grp_mem_family',
        boardId: 'landscape_memories',
        title: 'Family & Stories',
        description: 'Heritage, anecdotes, and recipes to pass on',
        color: 'peach',
        x: 60,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_mem_travel',
        boardId: 'landscape_memories',
        title: 'Places & Memories',
        description: 'Travel milestones and photo preservation',
        color: 'blue',
        x: 670,
        y: 60,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_mem_health',
        boardId: 'landscape_memories',
        title: 'Health & People to Call',
        description: 'Appointments, checkups, and staying in touch',
        color: 'green',
        x: 60,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
      {
        id: 'grp_mem_hobbies',
        boardId: 'landscape_memories',
        title: 'Hobbies & Life Lessons',
        description: 'Gardening, books, and quiet thoughts',
        color: 'yellow',
        x: 670,
        y: 360,
        width: 580,
        height: 270,
        collapsed: false,
      },
    ],
    notes: [
      {
        id: 'mem_n1',
        boardId: 'landscape_memories',
        title: 'Family Stories',
        type: 'concept',
        color: 'peach',
        content: "Grandfather's journey in 1952, how parents met in Mumbai, story of our first family garden.",
        x: 90,
        y: 120,
        width: 250,
        height: 180,
        rotation: -0.8,
        zIndex: 1,
        tags: ['family', 'heritage'],
        starred: true,
        pinned: false,
        groupId: 'grp_mem_family',
      },
      {
        id: 'mem_n2',
        boardId: 'landscape_memories',
        title: 'Recipes to Pass On',
        type: 'concept',
        color: 'yellow',
        content: "Grandma's slow-cooked tomato chutney with mustard seeds, homemade cardamom tea blend, holiday plum cake.",
        x: 360,
        y: 120,
        width: 250,
        height: 180,
        rotation: 1.2,
        zIndex: 2,
        tags: ['recipes', 'family'],
        starred: true,
        pinned: false,
        groupId: 'grp_mem_family',
      },
      {
        id: 'mem_n3',
        boardId: 'landscape_memories',
        title: 'Places I Have Visited',
        type: 'concept',
        color: 'blue',
        content: 'Shimla misty mornings (1984), Kerala backwaters on houseboat (2001), Kyoto cherry blossoms (2018).',
        x: 700,
        y: 120,
        width: 250,
        height: 180,
        rotation: -1.1,
        zIndex: 3,
        tags: ['travel', 'memories'],
        starred: true,
        pinned: false,
        groupId: 'grp_mem_travel',
      },
      {
        id: 'mem_n4',
        boardId: 'landscape_memories',
        title: 'Photos & Memories',
        type: 'concept',
        color: 'peach',
        content: 'Scan old photo albums from 1970–1990 into high-res digital copies for the children and grandchildren.',
        x: 970,
        y: 120,
        width: 250,
        height: 180,
        rotation: 0.9,
        zIndex: 4,
        tags: ['photos', 'preservation'],
        starred: false,
        pinned: false,
        groupId: 'grp_mem_travel',
      },
      {
        id: 'mem_n5',
        boardId: 'landscape_memories',
        title: 'People I Want to Call',
        type: 'task',
        color: 'green',
        content: 'Call uncle Suresh this Sunday afternoon, check in with old college friend Ramesh next Tuesday.',
        x: 90,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.4,
        zIndex: 5,
        tags: ['friends', 'stayintouch'],
        starred: true,
        pinned: false,
        groupId: 'grp_mem_health',
      },
      {
        id: 'mem_n6',
        boardId: 'landscape_memories',
        title: 'Important Dates & Health',
        type: 'quote',
        color: 'purple',
        content: 'Dr. Sharma annual checkup: Nov 12 at 10 AM. Eye exam: Dec 4. Family annual winter reunion: Dec 25.',
        quoteAuthor: 'Health & Calendar',
        x: 360,
        y: 420,
        width: 250,
        height: 180,
        rotation: -0.7,
        zIndex: 6,
        tags: ['health', 'dates'],
        starred: true,
        pinned: false,
        groupId: 'grp_mem_health',
      },
      {
        id: 'mem_n7',
        boardId: 'landscape_memories',
        title: 'Garden Ideas',
        type: 'idea',
        color: 'green',
        content: 'Plant fresh basil and mint in clay pots on the balcony. Prune rose bushes before winter.',
        x: 700,
        y: 420,
        width: 250,
        height: 180,
        rotation: -1.2,
        zIndex: 7,
        tags: ['garden', 'nature'],
        starred: false,
        pinned: false,
        groupId: 'grp_mem_hobbies',
      },
      {
        id: 'mem_n8',
        boardId: 'landscape_memories',
        title: 'Books I Enjoyed',
        type: 'concept',
        color: 'blue',
        content: 'The Old Man and the Sea, Ruskin Bond stories of the hills, Oliver Sacks essays on human nature.',
        x: 970,
        y: 420,
        width: 250,
        height: 180,
        rotation: 1.1,
        zIndex: 8,
        tags: ['books', 'reading'],
        starred: false,
        pinned: false,
        groupId: 'grp_mem_hobbies',
      },
    ],
    connections: [
      {
        id: 'conn_mem_1',
        boardId: 'landscape_memories',
        sourceId: 'mem_n1',
        targetId: 'mem_n4',
        type: 'arrow',
        label: 'archive',
      },
      {
        id: 'conn_mem_2',
        boardId: 'landscape_memories',
        sourceId: 'mem_n2',
        targetId: 'mem_n1',
        type: 'arrow',
        label: 'traditions',
      },
      {
        id: 'conn_mem_3',
        boardId: 'landscape_memories',
        sourceId: 'mem_n7',
        targetId: 'mem_n8',
        type: 'dashed',
        label: 'quiet time',
      },
    ],
  },

  // 7. EMPTY LANDSCAPE: Clean blank slate
  {
    board: {
      id: 'landscape_empty',
      name: 'Empty Landscape',
      description: 'A clean, blank canvas to start from scratch.',
      createdAt: 1726041606000,
      updatedAt: 1726041606000,
    },
    subtitle: 'A clean canvas ready for your thoughts.',
    groups: [],
    notes: [],
    connections: [],
  },
];
