import { EnvironmentDefinition, EnvironmentCategory } from '../types';

export const DEFAULT_ENVIRONMENT_ID = 'white-wall';

export const ENVIRONMENT_CATEGORIES: { id: EnvironmentCategory; name: string; description: string }[] = [
  { id: 'all', name: 'All Spaces', description: 'Browse all curated thinking spaces' },
  { id: 'minimal', name: 'Minimal', description: 'Clean, distraction-free neutral walls' },
  { id: 'study', name: 'Study & Academics', description: 'Chalkboards, cork boards, and study desks' },
  { id: 'creative', name: 'Creative Studio', description: 'Vibrant painted walls and artistic spaces' },
  { id: 'cozy', name: 'Cozy & Warm', description: 'Warm woods, soft beige, and inviting study nooks' },
  { id: 'professional', name: 'Professional', description: 'Modern office walls, dark slate, and blueprints' },
  { id: 'custom', name: 'Custom Wall', description: 'Pick your own color, brightness, and texture' },
];

export const ENVIRONMENTS: EnvironmentDefinition[] = [
  // --- MINIMAL ---
  {
    id: 'white-wall',
    name: 'White Wall',
    tagline: 'Clear space. Clear thinking.',
    description: 'A crisp, timeless off-white paper canvas with subtle spatial dot grid.',
    category: 'minimal',
    backgroundColor: '#FAF9F6',
    secondaryColor: '#F0EFEA',
    accentColor: '#1D4ED8',
    textColor: '#1E293B',
    gridColor: '#94A3B8',
    textureType: 'paper',
    lightingStyle: 'none',
    notePhysics: {
      shadowType: 'crisp',
      borderContrast: 'normal',
    },
    previewGradient: 'linear-gradient(135deg, #FAF9F6 0%, #EFECE6 100%)',
    isPopular: true,
  },
  {
    id: 'warm-white',
    name: 'Warm White',
    tagline: 'Soft natural paper finish.',
    description: 'Gentle warm eggshell tone that reduces eye strain during long thinking sessions.',
    category: 'minimal',
    backgroundColor: '#F7F5EE',
    secondaryColor: '#EDE9DE',
    accentColor: '#D97706',
    textColor: '#292524',
    gridColor: '#A8A29E',
    textureType: 'paper',
    lightingStyle: 'warm-ambient',
    notePhysics: {
      shadowType: 'soft',
      borderContrast: 'normal',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #FBF9F4 0%, #EDE8DC 100%)',
  },
  {
    id: 'soft-gray',
    name: 'Soft Gray Studio',
    tagline: 'Calm neutral contrast.',
    description: 'Refined architectural studio concrete with balanced contrast for colorful thoughts.',
    category: 'minimal',
    backgroundColor: '#EAECEF',
    secondaryColor: '#DFE2E6',
    accentColor: '#475569',
    textColor: '#0F172A',
    gridColor: '#94A3B8',
    textureType: 'plaster',
    lightingStyle: 'studio',
    notePhysics: {
      shadowType: 'crisp',
      borderContrast: 'normal',
    },
    previewGradient: 'linear-gradient(135deg, #F1F3F5 0%, #D8DCE0 100%)',
  },
  {
    id: 'paper-wall',
    name: 'Parchment Wall',
    tagline: 'Tactile notebook parchment.',
    description: 'Warm, textured cream paper evoking a giant boundless sketchbook.',
    category: 'minimal',
    backgroundColor: '#F5EFE6',
    secondaryColor: '#E8DCCF',
    accentColor: '#854D0E',
    textColor: '#3F2C1D',
    gridColor: '#B79F88',
    textureType: 'paper',
    lightingStyle: 'warm-ambient',
    notePhysics: {
      shadowType: 'soft',
      borderContrast: 'normal',
    },
    previewGradient: 'linear-gradient(135deg, #FAF5ED 0%, #E8DCBE 100%)',
  },

  // --- STUDY ---
  {
    id: 'green-chalkboard',
    name: 'Green Chalkboard',
    tagline: 'Think like you are in class.',
    description: 'Rich matte emerald slate with faint chalk grain and refined wooden trim.',
    category: 'study',
    backgroundColor: '#1B3B2B',
    secondaryColor: '#142E22',
    accentColor: '#34D399',
    textColor: '#F8FAFC',
    gridColor: '#2D5E46',
    textureType: 'chalk',
    frameType: 'chalkboard',
    lightingStyle: 'top-spot',
    notePhysics: {
      shadowType: 'chalk',
      borderContrast: 'high',
    },
    previewGradient: 'linear-gradient(135deg, #244C38 0%, #132D20 100%)',
    isPopular: true,
  },
  {
    id: 'cork-board',
    name: 'Cork Board',
    tagline: 'Pin ideas where you can see them.',
    description: 'Warm natural cork bulletin surface where notes feel physically pinned in place.',
    category: 'study',
    backgroundColor: '#C8A97E',
    secondaryColor: '#B59468',
    accentColor: '#92400E',
    textColor: '#451A03',
    gridColor: '#9A794F',
    textureType: 'cork',
    frameType: 'cork',
    lightingStyle: 'warm-ambient',
    notePhysics: {
      shadowType: 'pinned',
      pinVisible: true,
      borderContrast: 'normal',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #D8BC93 0%, #B29064 100%)',
    isPopular: true,
  },
  {
    id: 'wooden-study',
    name: 'Wooden Study Unit',
    tagline: 'A quiet space for deep work.',
    description: 'Deep walnut wood paneling evoking a private library alcove with soft focused lighting.',
    category: 'study',
    backgroundColor: '#38281F',
    secondaryColor: '#2B1E17',
    accentColor: '#F59E0B',
    textColor: '#FEF3C7',
    gridColor: '#533C2E',
    textureType: 'wood',
    frameType: 'wood',
    lightingStyle: 'desk-lamp',
    notePhysics: {
      shadowType: 'desk',
      borderContrast: 'high',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #4A3528 0%, #291D16 100%)',
    isPopular: true,
  },
  {
    id: 'study-desk',
    name: 'Study Desk Surface',
    tagline: 'Tactile timber workspace.',
    description: 'Natural blonde oak desk surface with ambient desk lighting.',
    category: 'study',
    backgroundColor: '#DFBE93',
    secondaryColor: '#CFAB7E',
    accentColor: '#78350F',
    textColor: '#3E200C',
    gridColor: '#B69163',
    textureType: 'wood',
    lightingStyle: 'desk-lamp',
    notePhysics: {
      shadowType: 'desk',
      borderContrast: 'normal',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #EBCEAA 0%, #CCA473 100%)',
  },

  // --- CREATIVE ---
  {
    id: 'painted-blue',
    name: 'Royal Blue Wall',
    tagline: 'Deep royal focus.',
    description: 'Immersive deep royal plaster wall that makes thoughts brightly pop.',
    category: 'creative',
    backgroundColor: '#1E293B',
    secondaryColor: '#0F172A',
    accentColor: '#38BDF8',
    textColor: '#F8FAFC',
    gridColor: '#334155',
    textureType: 'plaster',
    lightingStyle: 'top-spot',
    notePhysics: {
      shadowType: 'crisp',
      borderContrast: 'high',
    },
    previewGradient: 'linear-gradient(135deg, #2A3B54 0%, #111A29 100%)',
    isPopular: true,
  },
  {
    id: 'sage-green',
    name: 'Sage Green Wall',
    tagline: 'Gentle creative energy.',
    description: 'Muted botanical sage plaster bringing calm and clarity to complex mind maps.',
    category: 'creative',
    backgroundColor: '#8FA395',
    secondaryColor: '#7D9284',
    accentColor: '#166534',
    textColor: '#143821',
    gridColor: '#6E8375',
    textureType: 'plaster',
    lightingStyle: 'studio',
    notePhysics: {
      shadowType: 'soft',
      borderContrast: 'normal',
    },
    previewGradient: 'linear-gradient(135deg, #A1B6A7 0%, #768B7D 100%)',
  },
  {
    id: 'terracotta',
    name: 'Terracotta Wall',
    tagline: 'Earthy warmth for big ideas.',
    description: 'Rustic sun-baked clay plaster full of warmth and grounded inspiration.',
    category: 'creative',
    backgroundColor: '#C26B51',
    secondaryColor: '#AD5940',
    accentColor: '#7C2D12',
    textColor: '#FFF7ED',
    gridColor: '#964832',
    textureType: 'plaster',
    lightingStyle: 'warm-ambient',
    notePhysics: {
      shadowType: 'soft',
      borderContrast: 'normal',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #D47B60 0%, #A35038 100%)',
  },
  {
    id: 'dusty-pink',
    name: 'Dusty Rose Wall',
    tagline: 'Playful creative sanctuary.',
    description: 'Delicate vintage rose plaster with subtle warm ambient tones.',
    category: 'creative',
    backgroundColor: '#D6A6A4',
    secondaryColor: '#C4918F',
    accentColor: '#9D174D',
    textColor: '#50152C',
    gridColor: '#AF7B79',
    textureType: 'plaster',
    lightingStyle: 'warm-ambient',
    notePhysics: {
      shadowType: 'soft',
      borderContrast: 'normal',
    },
    previewGradient: 'linear-gradient(135deg, #E2B6B4 0%, #BD8987 100%)',
  },
  {
    id: 'lavender-wall',
    name: 'Lavender Wall',
    tagline: 'Calming pastel space.',
    description: 'Soft pastel violet creating a dream-like, tranquil thinking environment.',
    category: 'creative',
    backgroundColor: '#9DA0C7',
    secondaryColor: '#8C8FB8',
    accentColor: '#4338CA',
    textColor: '#1E1B4B',
    gridColor: '#787CA8',
    textureType: 'plaster',
    lightingStyle: 'studio',
    notePhysics: {
      shadowType: 'soft',
      borderContrast: 'normal',
    },
    previewGradient: 'linear-gradient(135deg, #AFB2D8 0%, #8588B0 100%)',
  },

  // --- COZY ---
  {
    id: 'wooden-wall',
    name: 'Cedar Timber Wall',
    tagline: 'Rustic warm timber.',
    description: 'Warm vertical cedar planks with rich wood grains and cozy cabin feel.',
    category: 'cozy',
    backgroundColor: '#5C3D2E',
    secondaryColor: '#492F23',
    accentColor: '#FDE68A',
    textColor: '#FFFBEB',
    gridColor: '#785341',
    textureType: 'wood',
    lightingStyle: 'warm-ambient',
    notePhysics: {
      shadowType: 'desk',
      borderContrast: 'high',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #704C3A 0%, #462D21 100%)',
  },
  {
    id: 'soft-beige',
    name: 'Soft Beige Nook',
    tagline: 'Cozy study corner.',
    description: 'Natural woven linen beige texture for calm and focused reflective thinking.',
    category: 'cozy',
    backgroundColor: '#E5DDCF',
    secondaryColor: '#D7CCA0',
    accentColor: '#78350F',
    textColor: '#422006',
    gridColor: '#BEB19C',
    textureType: 'paper',
    lightingStyle: 'warm-ambient',
    notePhysics: {
      shadowType: 'soft',
      borderContrast: 'normal',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #EDE5D8 0%, #D8CEBD 100%)',
  },
  {
    id: 'warm-studio',
    name: 'Warm Studio Dusk',
    tagline: 'Inviting creative den.',
    description: 'Golden hour twilight glow over warm terracotta and amber timber.',
    category: 'cozy',
    backgroundColor: '#A87A5B',
    secondaryColor: '#956749',
    accentColor: '#FEF08A',
    textColor: '#451A03',
    gridColor: '#80563A',
    textureType: 'plaster',
    lightingStyle: 'desk-lamp',
    notePhysics: {
      shadowType: 'desk',
      borderContrast: 'normal',
      ambientWarmth: true,
    },
    previewGradient: 'linear-gradient(135deg, #BA8C6D 0%, #8C5E40 100%)',
  },

  // --- PROFESSIONAL ---
  {
    id: 'white-office',
    name: 'White Office Wall',
    tagline: 'Crisp team board.',
    description: 'Modern architectural whiteboard studio for high-energy brainstorming and agile maps.',
    category: 'professional',
    backgroundColor: '#F1F5F9',
    secondaryColor: '#E2E8F0',
    accentColor: '#2563EB',
    textColor: '#0F172A',
    gridColor: '#CBD5E1',
    textureType: 'plaster',
    lightingStyle: 'studio',
    notePhysics: {
      shadowType: 'crisp',
      borderContrast: 'normal',
    },
    previewGradient: 'linear-gradient(135deg, #F8FAFC 0%, #E2E8F0 100%)',
  },
  {
    id: 'dark-slate',
    name: 'Dark Slate',
    tagline: 'High contrast night workspace.',
    description: 'Midnight obsidian slate with neon-accented thoughts for late night deep work.',
    category: 'professional',
    backgroundColor: '#0F172A',
    secondaryColor: '#020617',
    accentColor: '#60A5FA',
    textColor: '#F8FAFC',
    gridColor: '#1E293B',
    textureType: 'chalk',
    lightingStyle: 'top-spot',
    notePhysics: {
      shadowType: 'chalk',
      borderContrast: 'high',
    },
    previewGradient: 'linear-gradient(135deg, #1E293B 0%, #080C14 100%)',
    isPopular: true,
  },
  {
    id: 'blueprint-board',
    name: 'Blueprint Board',
    tagline: 'Architectural precision.',
    description: 'Prussian blue drafting board with crisp architectural cyan grid lines.',
    category: 'professional',
    backgroundColor: '#142B4D',
    secondaryColor: '#0D1E36',
    accentColor: '#38BDF8',
    textColor: '#E0F2FE',
    gridColor: '#1E4070',
    textureType: 'blueprint',
    lightingStyle: 'studio',
    notePhysics: {
      shadowType: 'crisp',
      borderContrast: 'high',
    },
    previewGradient: 'linear-gradient(135deg, #1A3864 0%, #0D1E38 100%)',
  },

  // --- CUSTOM ---
  {
    id: 'custom',
    name: 'Custom Wall Color',
    tagline: 'Make the space your own.',
    description: 'Choose your own custom color, brightness, and texture overlay.',
    category: 'custom',
    backgroundColor: '#E0E7FF',
    secondaryColor: '#C7D2FE',
    accentColor: '#4F46E5',
    textColor: '#1E1B4B',
    gridColor: '#A5B4FC',
    textureType: 'custom',
    lightingStyle: 'studio',
    notePhysics: {
      shadowType: 'crisp',
      borderContrast: 'normal',
    },
    previewGradient: 'conic-gradient(from 180deg at 50% 50%, #EF4444 0deg, #F59E0B 72deg, #10B981 144deg, #3B82F6 216deg, #8B5CF6 288deg, #EF4444 360deg)',
  },
];

export const NOTE_THEMES = [
  { id: 'classic', name: 'Classic Paper', description: 'Physical tape at top, subtle organic corner curl' },
  { id: 'clean', name: 'Clean Paper', description: 'Crisp stationery cards with clean drop shadow' },
  { id: 'handwritten', name: 'Handwritten Feel', description: 'Casual marker title and handwritten body vibe' },
  { id: 'minimal', name: 'Modern Minimal', description: 'Flat border with subtle inset line' },
] as const;

export function getEnvironmentById(id?: string): EnvironmentDefinition {
  if (!id) return ENVIRONMENTS[0];
  const env = ENVIRONMENTS.find((e) => e.id === id);
  return env || ENVIRONMENTS[0];
}
