import { StickyNote, Group } from '../types';

export interface Template {
  id: string;
  name: string;
  category: string;
  description: string;
  notes: Omit<StickyNote, 'id' | 'createdAt' | 'updatedAt'>[];
  groups: Omit<Group, 'id' | 'createdAt' | 'updatedAt'>[];
  connections: { sourceIndex: number; targetIndex: number; type: 'arrow' | 'line' | 'dashed'; label?: string }[];
}

export const TEMPLATES: Template[] = [
  {
    id: 'tutorial_guide',
    name: '🎓 Interactive Tutorial & Tour',
    category: 'Guide',
    description: 'Learn Thoughtscape with live interactive thoughts, WikiLinks, mistake breakdowns, and clusters.',
    groups: [
      {
        title: 'Cluster 1: Spatial Landscape Basics 🧭',
        description: 'Physical thoughts, direct editing, and WikiLinks',
        color: 'blue',
        x: 80,
        y: 80,
        width: 620,
        height: 520,
        collapsed: false,
      },
      {
        title: 'Cluster 2: Deep Thinking & Mental Models 🧠',
        description: 'Structured archetypes and learning pipeline',
        color: 'purple',
        x: 740,
        y: 80,
        width: 640,
        height: 520,
        collapsed: false,
      },
    ],
    notes: [
      {
        title: 'Welcome to Thoughtscape! 📌',
        content: 'You are physically arranging thoughts on your landscape.\n• Click any text directly to edit.\n• Drag empty canvas to Pan.\n• Check out [[First Mental Model]] to see WikiLinks!',
        type: 'concept',
        color: 'yellow',
        x: 120,
        y: 150,
        width: 250,
        height: 190,
        rotation: -1,
        zIndex: 1,
        tags: ['guide', 'basics'],
        starred: true,
        pinned: false,
        learningState: 'understood',
      },
      {
        title: 'Stationery Pad & Peeling 📄',
        content: 'Look at the floating stack in the bottom right ↘️\nClick a pastel color to pull and place a real thought onto your landscape!',
        type: 'idea',
        color: 'pink',
        x: 400,
        y: 150,
        width: 240,
        height: 190,
        rotation: 1.2,
        zIndex: 2,
        tags: ['gestures'],
        starred: false,
        pinned: false,
        learningState: 'new',
      },
      {
        title: 'Interactive Checklist ⚡',
        content: 'Try completing these beginner gestures:',
        type: 'task',
        color: 'green',
        x: 120,
        y: 370,
        width: 250,
        height: 200,
        rotation: 0.5,
        zIndex: 3,
        tags: ['tutorial'],
        starred: false,
        pinned: false,
        taskItems: [
          { id: 't1', text: 'Drag this thought around', completed: false },
          { id: 't2', text: 'Press ⌘K for Command Palette', completed: false },
          { id: 't3', text: 'Connect two thoughts with an arrow', completed: false },
        ],
      },
      {
        title: 'First Mental Model',
        content: 'Definition:\nA simplified mental framework explaining how something works.\n\nTakeaway:\nSpatial memory makes recall 3x stronger than linear text files.',
        type: 'concept',
        color: 'purple',
        x: 770,
        y: 150,
        width: 260,
        height: 210,
        rotation: -0.8,
        zIndex: 4,
        tags: ['mental-model'],
        starred: true,
        pinned: false,
        learningState: 'learning',
      },
      {
        title: 'Mistake Analysis ⚠️',
        content: 'Why anti-patterns make the best teachers:',
        type: 'mistake',
        color: 'peach',
        x: 1060,
        y: 150,
        width: 280,
        height: 220,
        rotation: 1,
        zIndex: 5,
        tags: ['learning'],
        starred: false,
        pinned: false,
        mistakeDetails: {
          whatIDid: 'Stored thoughts in complex nested database folders',
          whyWrong: 'Out of sight, out of mind — ideas were forgotten',
          correctApproach: 'Place active thoughts spatially on an open visual landscape',
          howToAvoid: 'Review spatial landscape daily with snapshots',
        },
      },
      {
        title: 'Active Recall Question ❓',
        content: 'What shortcut opens the global command palette?\n\nAnswer:\nCmd + K (or Ctrl + K on Windows). Try pressing it now!',
        type: 'question',
        color: 'blue',
        x: 770,
        y: 380,
        width: 260,
        height: 190,
        rotation: 0.5,
        zIndex: 6,
        tags: ['quiz'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Code Snippet Block 💻',
        content: '// Fast debounced save\nsaveWorkspace(state);',
        type: 'code',
        color: 'white',
        x: 1060,
        y: 390,
        width: 280,
        height: 180,
        rotation: -0.5,
        zIndex: 7,
        tags: ['code'],
        starred: false,
        pinned: false,
        codeLanguage: 'typescript',
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 3, type: 'arrow', label: 'references' },
      { sourceIndex: 0, targetIndex: 1, type: 'dashed', label: 'interacts' },
      { sourceIndex: 3, targetIndex: 4, type: 'arrow', label: 'prevents' },
      { sourceIndex: 3, targetIndex: 5, type: 'line', label: 'tests' },
    ],
  },
  {
    id: 'empty',
    name: 'Clean Landscape',
    category: 'Basic',
    description: 'A completely blank landscape to let your thoughts roam freely.',
    notes: [],
    groups: [],
    connections: [],
  },
  {
    id: 'dsa_map',
    name: 'DSA Problem Solving Landscape',
    category: 'Computer Science',
    description: 'Structured visual thinking for Data Structures & Algorithms patterns.',
    groups: [
      {
        title: 'Core Patterns',
        description: 'Key algorithmic problem-solving techniques',
        color: 'blue',
        x: 100,
        y: 80,
        width: 780,
        height: 480,
        collapsed: false,
      },
      {
        title: 'Data Structures Reference',
        description: 'Fundamental storage mechanisms',
        color: 'green',
        x: 100,
        y: 600,
        width: 780,
        height: 380,
        collapsed: false,
      }
    ],
    notes: [
      {
        title: 'Two Pointers Pattern',
        content: 'Used on sorted arrays or palindromes.\n• Opposite ends (e.g. 2Sum II)\n• Fast & Slow pointer (Cycle detection)\n• Sliding Window derivation',
        type: 'concept',
        color: 'blue',
        x: 140,
        y: 150,
        width: 210,
        height: 180,
        rotation: -1.2,
        zIndex: 1,
        tags: ['dsa', 'patterns'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Sliding Window',
        content: 'Maintains a sub-segment state.\n• Fixed size window (Sum of K items)\n• Dynamic size (Longest substring with K distinct chars)\n• Shrink condition check',
        type: 'concept',
        color: 'yellow',
        x: 390,
        y: 150,
        width: 210,
        height: 180,
        rotation: 1.5,
        zIndex: 2,
        tags: ['dsa', 'window'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Binary Search On Answer',
        content: 'When search space is monotonic: F F F T T T.\nFind first True condition.\n`mid = left + (right-left)//2`',
        type: 'code',
        color: 'purple',
        x: 640,
        y: 150,
        width: 210,
        height: 180,
        rotation: -0.8,
        zIndex: 3,
        tags: ['binarysearch'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Arrays & Dynamic Arrays',
        content: 'O(1) access by index.\nAmortized O(1) append.\nContiguous memory allocation.',
        type: 'normal',
        color: 'green',
        x: 140,
        y: 670,
        width: 210,
        height: 170,
        rotation: 1.1,
        zIndex: 4,
        tags: ['array'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Hash Maps & Sets',
        content: 'O(1) average lookup, insert, delete.\nHandle collisions via chaining or open addressing.\nCheck edge cases with empty keys.',
        type: 'normal',
        color: 'peach',
        x: 390,
        y: 670,
        width: 210,
        height: 170,
        rotation: -1.4,
        zIndex: 5,
        tags: ['hashmap'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Common Mistake Checklist',
        content: '• Index out of bounds (off by one)\n• Unhandled empty input []\n• Integer overflow on mid calc\n• Infinite loop in while(left <= right)',
        type: 'task',
        color: 'red',
        x: 640,
        y: 670,
        width: 210,
        height: 170,
        rotation: 0.9,
        zIndex: 6,
        tags: ['pitfalls'],
        starred: true,
        pinned: false,
      }
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1, type: 'arrow', label: 'extends to' },
      { sourceIndex: 1, targetIndex: 2, type: 'dashed', label: 'optimization' },
      { sourceIndex: 3, targetIndex: 0, type: 'arrow', label: 'applies on' }
    ]
  },
  {
    id: 'study_map',
    name: 'Deep Study & Concept Landscape',
    category: 'Learning',
    description: 'Master any topic through progressive breakdown and inquiry.',
    groups: [
      {
        title: 'Core Topic Study Landscape',
        description: 'Explore fundamentals down to questions and review',
        color: 'purple',
        x: 150,
        y: 80,
        width: 820,
        height: 520,
        collapsed: false,
      }
    ],
    notes: [
      {
        title: 'Central Topic: Distributed Systems',
        content: 'Consensus algorithms, replication strategies, and fault tolerance across untrusted networks.',
        type: 'concept',
        color: 'blue',
        x: 180,
        y: 150,
        width: 220,
        height: 160,
        rotation: -1.1,
        zIndex: 1,
        tags: ['systems', 'topic'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Core Invariants & Rules',
        content: '1. CAP Theorem trade-offs\n2. PACELC extension\n3. Quorum: R + W > N\n4. Idempotency on retry',
        type: 'idea',
        color: 'yellow',
        x: 450,
        y: 150,
        width: 220,
        height: 160,
        rotation: 1.4,
        zIndex: 2,
        tags: ['rules'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Raft Consensus Protocol',
        content: 'Leader election, Log replication, Safety guarantees.\nHeartbeat timers prevent split-vote.',
        type: 'code',
        color: 'green',
        x: 720,
        y: 150,
        width: 220,
        height: 160,
        rotation: -0.6,
        zIndex: 3,
        tags: ['raft'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Open Questions & Doubts',
        content: '• How does dynamic membership change handle split brain?\n• Exact difference between 2PC and 3PC latency?',
        type: 'question',
        color: 'purple',
        x: 320,
        y: 370,
        width: 230,
        height: 160,
        rotation: 1.2,
        zIndex: 4,
        tags: ['doubts'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Next Action Items',
        content: '• Read Raft paper section 5\n• Implement simple in-memory log\n• Benchmark network partitions',
        type: 'task',
        color: 'pink',
        x: 600,
        y: 370,
        width: 230,
        height: 160,
        rotation: -1.5,
        zIndex: 5,
        tags: ['action'],
        starred: false,
        pinned: false,
      }
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1, type: 'arrow', label: 'governed by' },
      { sourceIndex: 1, targetIndex: 2, type: 'arrow', label: 'implemented via' },
      { sourceIndex: 0, targetIndex: 3, type: 'dashed', label: 'spawns' },
      { sourceIndex: 3, targetIndex: 4, type: 'arrow', label: 'resolve via' }
    ]
  },
  {
    id: 'project_brainstorm',
    name: 'Project Brainstorm Landscape',
    category: 'Creative',
    description: 'Map out problem statements, brainstorm features, and plan architecture.',
    groups: [
      {
        title: 'Brainstorm Landscape',
        description: 'Ideas, Architecture & Launch Plan',
        color: 'orange',
        x: 120,
        y: 80,
        width: 800,
        height: 480,
        collapsed: false,
      }
    ],
    notes: [
      {
        title: 'Problem Statement',
        content: 'Users get overwhelmed by complex project managers and just want a tactile landscape to organize their visual thinking.',
        type: 'question',
        color: 'red',
        x: 150,
        y: 150,
        width: 220,
        height: 170,
        rotation: -1.3,
        zIndex: 1,
        tags: ['problem'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Key Differentiators',
        content: '• Physical paper feel\n• Peeling note animation\n• Curved connection arrows\n• 100% local persistence',
        type: 'idea',
        color: 'yellow',
        x: 410,
        y: 150,
        width: 220,
        height: 170,
        rotation: 1.1,
        zIndex: 2,
        tags: ['features'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Tech Architecture',
        content: '• React 19 + TypeScript\n• Tailwind CSS for rich paper styling\n• SVG Dynamic Bezier arrows\n• IndexedDB debounced storage',
        type: 'code',
        color: 'blue',
        x: 670,
        y: 150,
        width: 220,
        height: 170,
        rotation: -0.7,
        zIndex: 3,
        tags: ['tech'],
        starred: false,
        pinned: false,
      },
      {
        title: 'v1 Release Checklist',
        content: '• Full export to PNG & PDF\n• Undo/redo history\n• Search & Tag filter\n• Responsive layout',
        type: 'task',
        color: 'green',
        x: 410,
        y: 360,
        width: 230,
        height: 160,
        rotation: 0.8,
        zIndex: 4,
        tags: ['launch'],
        starred: true,
        pinned: false,
      }
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1, type: 'arrow', label: 'inspires' },
      { sourceIndex: 1, targetIndex: 2, type: 'arrow', label: 'built with' },
      { sourceIndex: 1, targetIndex: 3, type: 'arrow', label: 'targets' }
    ]
  },
  {
    id: 'mistake_journal',
    name: 'Mistake Journal & Revision Landscape',
    category: 'Study',
    description: 'Transform debugging blunders and exam mistakes into permanent mastery.',
    groups: [
      {
        title: 'Common Pitfalls & Fixes',
        description: 'Analyzing root causes and preventative rules',
        color: 'red',
        x: 120,
        y: 80,
        width: 820,
        height: 520,
        collapsed: false,
      }
    ],
    notes: [
      {
        title: 'Off-by-One in Binary Search',
        content: 'Failed test case when target is at index 0 or N-1.',
        type: 'mistake',
        color: 'red',
        x: 150,
        y: 150,
        width: 250,
        height: 220,
        rotation: -1.2,
        zIndex: 1,
        tags: ['mistake', 'dsa'],
        starred: true,
        pinned: false,
        mistakeDetails: {
          whatIDid: 'Used `right = arr.length` with `while(left <= right)`',
          whyWrong: 'Caused ArrayIndexOutOfBoundsException when target not found.',
          correctApproach: 'Pair `right = arr.length - 1` with `while(left <= right)` OR `right = arr.length` with `while(left < right)`',
          howToAvoid: 'Check 1-element and 2-element edge cases before submitting.',
        }
      },
      {
        title: 'Golden Rule of State Invariants',
        content: '"Make illegal states unrepresentable in the type system whenever possible."',
        type: 'quote',
        quoteAuthor: 'Yaron Minsky',
        color: 'yellow',
        x: 440,
        y: 150,
        width: 240,
        height: 190,
        rotation: 1.3,
        zIndex: 2,
        tags: ['quote', 'architecture'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Revision Checklist Before Contests',
        content: '• Check 64-bit integer overflow\n• Verify recursion base cases\n• Reset global buffers between test cases',
        type: 'task',
        color: 'green',
        x: 710,
        y: 150,
        width: 210,
        height: 190,
        rotation: -0.5,
        zIndex: 3,
        tags: ['checklist'],
        starred: false,
        pinned: false,
      }
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1, type: 'dashed', label: 'prevented by' },
      { sourceIndex: 0, targetIndex: 2, type: 'arrow', label: 'added to' }
    ]
  }
];
