import { StickyNote, Group } from '../types';
import { DEMO_LANDSCAPES } from './demoLandscapes';

export interface Template {
  id: string;
  name: string;
  category: 'Overview' | 'Study' | 'Work' | 'Personal' | 'Life' | 'Technical' | 'Creative' | 'Basic';
  description: string;
  notes: Omit<StickyNote, 'id' | 'createdAt' | 'updatedAt'>[];
  groups: Omit<Group, 'id' | 'createdAt' | 'updatedAt'>[];
  connections: { sourceIndex: number; targetIndex: number; type: 'arrow' | 'line' | 'dashed'; label?: string }[];
}

export const TEMPLATES: Template[] = [
  // 1. Welcome to Thoughtscape (Overview)
  {
    id: 'welcome_tour',
    name: '🌟 Welcome to Thoughtscape',
    category: 'Overview',
    description: 'A little tour of what you can build across school, college, work and life.',
    groups: DEMO_LANDSCAPES[0].groups.map((g) => ({
      title: g.title,
      description: g.description,
      color: g.color,
      x: g.x,
      y: g.y,
      width: g.width,
      height: g.height,
      collapsed: g.collapsed,
    })),
    notes: DEMO_LANDSCAPES[0].notes.map((n) => ({
      title: n.title,
      content: n.content,
      type: n.type,
      color: n.color,
      x: n.x,
      y: n.y,
      width: n.width,
      height: n.height,
      rotation: n.rotation,
      zIndex: n.zIndex,
      tags: n.tags,
      starred: n.starred,
      pinned: n.pinned,
      taskItems: n.taskItems,
      mistakeDetails: n.mistakeDetails,
      quoteAuthor: n.quoteAuthor,
      learningState: n.learningState,
    })),
    connections: [
      { sourceIndex: 0, targetIndex: 1, type: 'arrow', label: 'steps' },
      { sourceIndex: 3, targetIndex: 5, type: 'arrow', label: 'inspires' },
      { sourceIndex: 7, targetIndex: 6, type: 'arrow', label: 'action items' },
      { sourceIndex: 10, targetIndex: 9, type: 'arrow', label: 'moments' },
    ],
  },

  // 2. Class 10 — Board Preparation (Study)
  {
    id: 'class10',
    name: '🎓 Class 10 — Board Preparation',
    category: 'Study',
    description: 'Organize revision, questions and exam plans across subjects.',
    groups: DEMO_LANDSCAPES[1].groups.map((g) => ({
      title: g.title,
      description: g.description,
      color: g.color,
      x: g.x,
      y: g.y,
      width: g.width,
      height: g.height,
      collapsed: g.collapsed,
    })),
    notes: DEMO_LANDSCAPES[1].notes.map((n) => ({
      title: n.title,
      content: n.content,
      type: n.type,
      color: n.color,
      x: n.x,
      y: n.y,
      width: n.width,
      height: n.height,
      rotation: n.rotation,
      zIndex: n.zIndex,
      tags: n.tags,
      starred: n.starred,
      pinned: n.pinned,
      taskItems: n.taskItems,
      mistakeDetails: n.mistakeDetails,
      quoteAuthor: n.quoteAuthor,
      learningState: n.learningState,
    })),
    connections: [
      { sourceIndex: 0, targetIndex: 8, type: 'arrow', label: 'revise' },
      { sourceIndex: 3, targetIndex: 9, type: 'arrow', label: 'solve' },
      { sourceIndex: 10, targetIndex: 8, type: 'arrow', label: 'follow up' },
    ],
  },

  // 3. College Semester (Study)
  {
    id: 'college',
    name: '🏛️ College Semester',
    category: 'Study',
    description: 'Keep projects, assignments, research and career ideas connected.',
    groups: DEMO_LANDSCAPES[2].groups.map((g) => ({
      title: g.title,
      description: g.description,
      color: g.color,
      x: g.x,
      y: g.y,
      width: g.width,
      height: g.height,
      collapsed: g.collapsed,
    })),
    notes: DEMO_LANDSCAPES[2].notes.map((n) => ({
      title: n.title,
      content: n.content,
      type: n.type,
      color: n.color,
      x: n.x,
      y: n.y,
      width: n.width,
      height: n.height,
      rotation: n.rotation,
      zIndex: n.zIndex,
      tags: n.tags,
      starred: n.starred,
      pinned: n.pinned,
      taskItems: n.taskItems,
      mistakeDetails: n.mistakeDetails,
      quoteAuthor: n.quoteAuthor,
      learningState: n.learningState,
    })),
    connections: [
      { sourceIndex: 2, targetIndex: 5, type: 'arrow', label: 'references' },
      { sourceIndex: 0, targetIndex: 6, type: 'arrow', label: 'prepares for' },
      { sourceIndex: 1, targetIndex: 4, type: 'arrow', label: 'unblocks' },
    ],
  },

  // 4. Work & Projects (Work)
  {
    id: 'work',
    name: '💼 Work & Projects',
    category: 'Work',
    description: 'Bring tasks, meetings and project thinking together.',
    groups: DEMO_LANDSCAPES[3].groups.map((g) => ({
      title: g.title,
      description: g.description,
      color: g.color,
      x: g.x,
      y: g.y,
      width: g.width,
      height: g.height,
      collapsed: g.collapsed,
    })),
    notes: DEMO_LANDSCAPES[3].notes.map((n) => ({
      title: n.title,
      content: n.content,
      type: n.type,
      color: n.color,
      x: n.x,
      y: n.y,
      width: n.width,
      height: n.height,
      rotation: n.rotation,
      zIndex: n.zIndex,
      tags: n.tags,
      starred: n.starred,
      pinned: n.pinned,
      taskItems: n.taskItems,
      mistakeDetails: n.mistakeDetails,
      quoteAuthor: n.quoteAuthor,
      learningState: n.learningState,
    })),
    connections: [
      { sourceIndex: 2, targetIndex: 1, type: 'arrow', label: 'generates' },
      { sourceIndex: 3, targetIndex: 0, type: 'arrow', label: 'guides' },
      { sourceIndex: 4, targetIndex: 5, type: 'arrow', label: 'discuss in 1:1' },
    ],
  },

  // 5. Personal Life (Personal)
  {
    id: 'personal',
    name: '🏡 Personal Life',
    category: 'Personal',
    description: 'Plans, ideas, memories and things worth remembering.',
    groups: DEMO_LANDSCAPES[4].groups.map((g) => ({
      title: g.title,
      description: g.description,
      color: g.color,
      x: g.x,
      y: g.y,
      width: g.width,
      height: g.height,
      collapsed: g.collapsed,
    })),
    notes: DEMO_LANDSCAPES[4].notes.map((n) => ({
      title: n.title,
      content: n.content,
      type: n.type,
      color: n.color,
      x: n.x,
      y: n.y,
      width: n.width,
      height: n.height,
      rotation: n.rotation,
      zIndex: n.zIndex,
      tags: n.tags,
      starred: n.starred,
      pinned: n.pinned,
      taskItems: n.taskItems,
      mistakeDetails: n.mistakeDetails,
      quoteAuthor: n.quoteAuthor,
      learningState: n.learningState,
    })),
    connections: [
      { sourceIndex: 1, targetIndex: 5, type: 'arrow', label: 'needs items' },
      { sourceIndex: 2, targetIndex: 3, type: 'arrow', label: 'planned for' },
      { sourceIndex: 7, targetIndex: 3, type: 'arrow', label: 'inspires' },
    ],
  },

  // 6. My Life & Memories (Life)
  {
    id: 'memories',
    name: '📜 My Life & Memories',
    category: 'Life',
    description: 'A visual place for experiences, family stories, and quiet reflections.',
    groups: DEMO_LANDSCAPES[5].groups.map((g) => ({
      title: g.title,
      description: g.description,
      color: g.color,
      x: g.x,
      y: g.y,
      width: g.width,
      height: g.height,
      collapsed: g.collapsed,
    })),
    notes: DEMO_LANDSCAPES[5].notes.map((n) => ({
      title: n.title,
      content: n.content,
      type: n.type,
      color: n.color,
      x: n.x,
      y: n.y,
      width: n.width,
      height: n.height,
      rotation: n.rotation,
      zIndex: n.zIndex,
      tags: n.tags,
      starred: n.starred,
      pinned: n.pinned,
      taskItems: n.taskItems,
      mistakeDetails: n.mistakeDetails,
      quoteAuthor: n.quoteAuthor,
      learningState: n.learningState,
    })),
    connections: [
      { sourceIndex: 0, targetIndex: 3, type: 'arrow', label: 'archive' },
      { sourceIndex: 1, targetIndex: 0, type: 'arrow', label: 'traditions' },
      { sourceIndex: 6, targetIndex: 7, type: 'dashed', label: 'quiet time' },
    ],
  },

  // 7. DSA Problem Solving (Technical - Kept as optional template)
  {
    id: 'dsa_map',
    name: '💻 DSA Problem Solving',
    category: 'Technical',
    description: 'Structured algorithmic problem-solving patterns and data structures.',
    groups: [
      {
        title: 'Core Patterns',
        description: 'Key algorithmic problem-solving techniques',
        color: 'blue',
        x: 100,
        y: 80,
        width: 780,
        height: 480,
        collapsed: false,
      },
      {
        title: 'Data Structures Reference',
        description: 'Fundamental storage mechanisms',
        color: 'green',
        x: 100,
        y: 600,
        width: 780,
        height: 380,
        collapsed: false,
      },
    ],
    notes: [
      {
        title: 'Two Pointers Pattern',
        content: 'Used on sorted arrays or palindromes.\n• Opposite ends (e.g. 2Sum II)\n• Fast & Slow pointer (Cycle detection)\n• Sliding Window derivation',
        type: 'concept',
        color: 'blue',
        x: 140,
        y: 150,
        width: 210,
        height: 180,
        rotation: -1.2,
        zIndex: 1,
        tags: ['dsa', 'patterns'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Sliding Window',
        content: 'Maintains a sub-segment state.\n• Fixed size window (Sum of K items)\n• Dynamic size (Longest substring with K distinct chars)\n• Shrink condition check',
        type: 'concept',
        color: 'yellow',
        x: 390,
        y: 150,
        width: 210,
        height: 180,
        rotation: 1.5,
        zIndex: 2,
        tags: ['dsa', 'window'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Binary Search On Answer',
        content: 'When search space is monotonic: F F F T T T.\nFind first True condition.\n`mid = left + (right-left)//2`',
        type: 'code',
        color: 'purple',
        x: 640,
        y: 150,
        width: 210,
        height: 180,
        rotation: -0.8,
        zIndex: 3,
        tags: ['binarysearch'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Arrays & Dynamic Arrays',
        content: 'O(1) access by index.\nAmortized O(1) append.\nContiguous memory allocation.',
        type: 'normal',
        color: 'green',
        x: 140,
        y: 670,
        width: 210,
        height: 170,
        rotation: 1.1,
        zIndex: 4,
        tags: ['array'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Hash Maps & Sets',
        content: 'O(1) average lookup, insert, delete.\nHandle collisions via chaining or open addressing.\nCheck edge cases with empty keys.',
        type: 'normal',
        color: 'peach',
        x: 390,
        y: 670,
        width: 210,
        height: 170,
        rotation: -1.4,
        zIndex: 5,
        tags: ['hashmap'],
        starred: false,
        pinned: false,
      },
      {
        title: 'Common Mistake Checklist',
        content: '• Index out of bounds (off by one)\n• Unhandled empty input []\n• Integer overflow on mid calc\n• Infinite loop in while(left <= right)',
        type: 'task',
        color: 'red',
        x: 640,
        y: 670,
        width: 210,
        height: 170,
        rotation: 0.9,
        zIndex: 6,
        tags: ['pitfalls'],
        starred: true,
        pinned: false,
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1, type: 'arrow', label: 'extends to' },
      { sourceIndex: 1, targetIndex: 2, type: 'dashed', label: 'optimization' },
      { sourceIndex: 3, targetIndex: 0, type: 'arrow', label: 'applies on' },
    ],
  },

  // 8. Project Brainstorm (Creative)
  {
    id: 'project_brainstorm',
    name: '💡 Project Brainstorm',
    category: 'Creative',
    description: 'Map out problem statements, brainstorm features, and plan architecture.',
    groups: [
      {
        title: 'Brainstorm Landscape',
        description: 'Ideas, Architecture & Launch Plan',
        color: 'orange',
        x: 120,
        y: 80,
        width: 800,
        height: 480,
        collapsed: false,
      },
    ],
    notes: [
      {
        title: 'Problem Statement',
        content: 'Users get overwhelmed by complex project managers and just want a tactile landscape to organize their visual thinking.',
        type: 'question',
        color: 'red',
        x: 150,
        y: 150,
        width: 220,
        height: 170,
        rotation: -1.3,
        zIndex: 1,
        tags: ['problem'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Key Differentiators',
        content: '• Physical paper feel\n• Peeling note animation\n• Curved connection arrows\n• 100% local persistence',
        type: 'idea',
        color: 'yellow',
        x: 410,
        y: 150,
        width: 220,
        height: 170,
        rotation: 1.1,
        zIndex: 2,
        tags: ['features'],
        starred: true,
        pinned: false,
      },
      {
        title: 'Tech Architecture',
        content: '• React 19 + TypeScript\n• Tailwind CSS for rich paper styling\n• SVG Dynamic Bezier arrows\n• IndexedDB debounced storage',
        type: 'code',
        color: 'blue',
        x: 670,
        y: 150,
        width: 220,
        height: 170,
        rotation: -0.7,
        zIndex: 3,
        tags: ['tech'],
        starred: false,
        pinned: false,
      },
      {
        title: 'v1 Release Checklist',
        content: '• Full export to PNG & PDF\n• Undo/redo history\n• Search & Tag filter\n• Responsive layout',
        type: 'task',
        color: 'green',
        x: 410,
        y: 360,
        width: 230,
        height: 160,
        rotation: 0.8,
        zIndex: 4,
        tags: ['launch'],
        starred: true,
        pinned: false,
      },
    ],
    connections: [
      { sourceIndex: 0, targetIndex: 1, type: 'arrow', label: 'inspires' },
      { sourceIndex: 1, targetIndex: 2, type: 'arrow', label: 'built with' },
      { sourceIndex: 1, targetIndex: 3, type: 'arrow', label: 'targets' },
    ],
  },

  // 9. Empty Landscape (Basic)
  {
    id: 'empty',
    name: '✨ Empty Landscape',
    category: 'Basic',
    description: 'A completely blank canvas to start from scratch.',
    notes: [],
    groups: [],
    connections: [],
  },
];
