import { TutorialStepConfig } from '../types/tutorial';

export const TUTORIAL_STEPS: TutorialStepConfig[] = [
  {
    id: 'step_1_canvas',
    stepNumber: 1,
    totalSteps: 14,
    targetSelector: '[data-tutorial="canvas"]',
    title: 'Your Thoughtscape',
    description: 'This is your visual thinking space.\nPlace thoughts wherever they make sense to you.',
    placement: 'center',
    actionHint: 'Drag empty canvas to pan • Scroll to zoom',
  },
  {
    id: 'step_2_add_note',
    stepNumber: 2,
    totalSteps: 14,
    targetSelector: '[data-tutorial="add-note"]',
    title: 'Add a Thought',
    description: 'Capture anything that comes to mind.',
    placement: 'left',
    actionHint: "Click to choose your thought's color",
  },
  {
    id: 'step_3_color_select',
    stepNumber: 3,
    totalSteps: 14,
    targetSelector: '[data-tutorial="color-picker"]',
    title: 'Give it a color',
    description: 'Colors can help you create your own visual language.\n\n• Yellow → General thoughts\n• Blue → Key concepts\n• Purple → Questions\n• Green → Solutions',
    placement: 'left',
    requiresInteraction: true,
    interactionPrompt: 'Click any color to place your thought →',
    interactionSuccessText: '✓ Thought entering landscape...',
  },
  {
    id: 'step_4_animation',
    stepNumber: 4,
    totalSteps: 14,
    targetSelector: '[data-tutorial="note-demo-1"]',
    title: 'A Thought Enters the Landscape ✨',
    description: 'Paper lifts, separates from the stack, and settles into your Thoughtscape.',
    placement: 'right',
  },
  {
    id: 'step_5_edit_note',
    stepNumber: 5,
    totalSteps: 14,
    targetSelector: '[data-tutorial="note-demo-1"]',
    title: 'Express Your Thoughts',
    description: 'Click a thought and write freely.\nUse titles, markdown, tags, and [[Thought Links]].',
    placement: 'right',
    actionHint: 'Click text or title to edit directly',
  },
  {
    id: 'step_6_drag_note',
    stepNumber: 6,
    totalSteps: 14,
    targetSelector: '[data-tutorial="note-demo-1"]',
    title: 'Move your thoughts',
    description: 'Space can carry meaning.\nPut related ideas near each other.',
    placement: 'right',
    requiresInteraction: true,
    interactionPrompt: 'Try dragging the thought somewhere else →',
    interactionSuccessText: '✓ Nice spatial placement!',
  },
  {
    id: 'step_7_resize_note',
    stepNumber: 7,
    totalSteps: 14,
    targetSelector: '[data-tutorial="note-demo-1-resize"]',
    title: 'Resize for Emphasis',
    description: 'Make big ideas prominent. Keep quick thoughts compact.',
    placement: 'top',
    requiresInteraction: true,
    interactionPrompt: 'Drag the corner grip to resize →',
    interactionSuccessText: '✓ Perfect size!',
  },
  {
    id: 'step_8_color_change',
    stepNumber: 8,
    totalSteps: 14,
    targetSelector: '[data-tutorial="note-demo-1"]',
    title: 'Evolve Your Color Language',
    description: "You can change the color of a thought at any time as your ideas evolve.",
    placement: 'right',
  },
  {
    id: 'step_9_connect_notes',
    stepNumber: 9,
    totalSteps: 14,
    targetSelector: '[data-tutorial="note-demo-1-connect"]',
    title: 'Connect your thoughts',
    description: 'Show how one idea relates to another.\n\nArray ➔ Two Pointers',
    placement: 'right',
  },
  {
    id: 'step_10_group_notes',
    stepNumber: 10,
    totalSteps: 14,
    targetSelector: '[data-tutorial="group-demo"]',
    title: 'Create a landscape cluster',
    description: 'Gather related thoughts into a larger conceptual area.\n\nFor example:\nDSA ├── Arrays ├── Hashing └── Sliding Window',
    placement: 'top',
  },
  {
    id: 'step_11_search',
    stepNumber: 11,
    totalSteps: 14,
    targetSelector: '[data-tutorial="search-btn"]',
    title: 'Explore your Thoughtscape',
    description: 'Find any thought instantly. The camera moves straight to your concept.',
    placement: 'bottom',
  },
  {
    id: 'step_12_undo_redo',
    stepNumber: 12,
    totalSteps: 14,
    targetSelector: '[data-tutorial="undo-redo-btn"]',
    title: 'Experiment Freely',
    description: 'Made a mistake? Use Undo (⌘Z) and Redo (⌘⇧Z) to move back and forth through your changes safely.',
    placement: 'bottom',
  },
  {
    id: 'step_13_export',
    stepNumber: 13,
    totalSteps: 14,
    targetSelector: '[data-tutorial="export-btn"]',
    title: 'Take your Thoughtscape with you',
    description: 'Export it as PDF, PNG or a complete portable backup.',
    placement: 'bottom',
  },
  {
    id: 'step_14_command_palette',
    stepNumber: 14,
    totalSteps: 14,
    targetSelector: '[data-tutorial="command-palette-btn"]',
    title: 'Explore Thoughtscape (Cmd + K)',
    description: 'Press Cmd/Ctrl + K to search, add thoughts, create clusters, or run tools instantly.',
    placement: 'bottom',
  },
];
